#!/bin/sh

echo "/* automatically generated by sed scripts from the c source named below: */" | cat - $1 | sed 's/cdd_/__XXXXXX__/g' | sed 's/dd_/ddf_/g'| sed 's/__XXXXXX__/cdd_/g' | sed 's/mytype/myfloat/g' | sed 's/GMPRATIONAL/ddf_GMPRATIONAL/g' | sed 's/_H$/_HF/g' | sed 's/_H /_HF /g' | sed 's/\.h"/_f\.h"/g' | sed 's/_f_f.h"/_f.h"/g' | sed 's/setoper_f.h"/setoper.h"/g' | sed 's/mpir_f.h"/mpir.h"/g' | sed 's/gmp_f.h"/gmp.h"/g' | sed 's/ddf_ARITHMETIC/ddf_ddf_ARITHMETIC/g' | sed 's/ddf_CDOUBLE/ddf_ddf_CDOUBLE/g' | sed 's/__CDDMP_HF/_CDDMP_HF/g' | sed 's/__CDDTYPES_HF/_CDDTYPES_HF/g'
